NDF-Poli-USP/spyro

- spyro/receivers/Receivers.py
- spyro/solvers/helpers.py
- test/test_newat.py
Added new point interpolation that uses CG or KMV elements and is also more integrated with Firedrake. If another type of element is needed in the future only a few lines of code calling it from FIAT is required.
> Updated receivers from dev repository

- setup.py
- spyro/io/io.py
> adding io routines

- spyro/solvers/leapfrog.py
- spyro/solvers/leapfrog_adjoint.py
* In physical domain, the gradient does not depends of  the auxiliary functions because the damping functions are equal to zero
> simplification of gradient

- benchmarks/benchmark_cuboid.py
> adding cuboid benchmark

- README.md
- errorfinder.py
- gridsweepHeterogenous.py
- gridsweepHomogeneous.py
- plotforeagePointSourceWithDisk.py
- plotforeagePointSourceWithDiskNoFilter.py
- receiver_comparison.py
- run_grid_point_calculation.py
- run_leapfrog.py
- spyro/io/io.py
- spyro/receivers/Receivers.py
- spyro/solvers/leapfrog.py
- spyro/solvers/leapfrog_adjoint.py
- spyro/sources/Sources.py
- spyro/sources/__init__.py
- spyro/tools/grid_point_calculator.py
- spyro/tools/input_models.py
Started to merge all branches related to tools package
> Adding fixed point options

- cleanup.sh
- spyro/receivers/Receivers.py
- spyro/solvers/leapfrog.py
- spyro/solvers/leapfrog_adjoint.py
- spyro/sources/Sources.py
- spyro/sources/__init__.py
- spyro/utils/estimate_timestep.py
- spyro/utils/utils.py
- test/test_gradient_taylor_remainder.py
> Revert "New source"

- cleanup.sh
- spyro/receivers/Receivers.py
- spyro/solvers/leapfrog.py
- spyro/solvers/leapfrog_adjoint.py
- spyro/sources/Sources.py
- spyro/sources/__init__.py
- spyro/utils/estimate_timestep.py
- spyro/utils/utils.py
- test/test_gradient_taylor_remainder.py
> Revert "Revert "New source""

- spyro/receivers/Receivers.py
- spyro/solvers/gradient.py
- spyro/utils/utils.py
- test/inputfiles/Model1_gradient_2d.py
- test/not_a_test.py
- test/test_gradient.py
* and new FD test to check gradient
> more fixes to gradient

- spyro/solvers/forward.py
- spyro/sources/Sources.py
Just a small source fix. No supershot supported yet, unfortunately this will have to wait until I figure out how to deal with the ensemble communicator.
> Small source fix

- demos/run_fwi.py
- spyro/utils/utils.py
* to cost functional and gradient calculation when performing fwi.
> adds a simple regularization

- README.md
- benchmarks/benchmark_2d.py
- benchmarks/benchmark_3d.py
- spyro/__init__.py
- spyro/utils/geometry_creation.py
Adding new figure for scaling benchmark and the relevant .py files in the benchmark folder. However, I am still waiting for mintrop to validate the .py files in the benchmark folder.
> Read me update

- spyro/domains/quadrature.py
- spyro/domains/space.py
- spyro/receivers/Receivers.py
- spyro/sources/Sources.py
- spyro/tools/input_models.py
- test/inputfiles/Model1_2d_CG.py
- test/inputfiles/Model1_2d_DG.py
- test/inputfiles/Model1_3d_CG.py
- test/inputfiles/Model1_3d_DG.py
- test/inputfiles/Model1_gradient_2d_pml.py
- test/inputfiles/Model1_gradient_3d_pml.py
- test/inputfiles/ModelMMS_2d_CG.py
- test/inputfiles/ModelMMS_2d_DG.py
- test/inputfiles/ModelMMS_3d_CG.py
- test/inputfiles/ModelMMS_3d_DG.py
- test/model.py
- test/test_newat.py
This PR adds 2D spectral quadrilateral elements with GLL nodes and under-integration. I still have to finish the 3D hexa implementation
> Adding 2 d quadrilateral elements

- .github/workflows/python-tests.yml
- spyro/tools/grid_point_calculator.py
- spyro/utils/utils.py
- test/test_MMS.py
- test/test_gradient.py
- test/test_newat.py
- test/test_readmesh.py
- test/test_sources.py
- test/test_tools.py
- test_tools.py
This update changes how tests are run, adding support for parallel testing. We can now run tests in parallel (with one test per core), reducing runtime and parallel tests (with more than one core per test). This reduces total runtime of tests and also allows us to test parallelism.
> Adding parallel tests

- spyro/domains/quadrature.py
- spyro/io/io.py
- test/test_MMS.py
- test/test_io.py
Trying to improve code coverage by commenting out some unsused sections and adding tests
> Improving coverage

- spyro/io/io.py
- spyro/plots/plots.py
Simple PR to enable saves, loads and plots in parallel while using custom file names.
> added parallel support to custom file names

- .github/workflows/python-tests.yml
- demos/run_fwi.py
- paper/run_fwi_2d.py
- paper/run_fwi_3d.py
- spyro/solvers/forward.py
- spyro/solvers/forward_AD.py
- spyro/solvers/gradient.py
- spyro/utils/estimate_timestep.py
- test/not_a_test.py
- test/test_gradient.py
- test/test_gradient_3d.py
Changing python-tests.yml to reflect file locations in new self hosted runner. Also updated code and tests to be compatible with latest Firedrake version.
> Updating GitHub runner

- spyro/domains/quadrature.py
- spyro/domains/space.py
- spyro/io/io.py
- spyro/pml/damping.py
- spyro/receivers/Receivers.py
- spyro/solvers/helpers.py
- spyro/sources/Sources.py
- spyro/tools/gradient_test_ad.py
- spyro/tools/grid_point_calculator.py
- spyro/utils/estimate_timestep.py
- spyro/utils/utils.py
Doesn't change any code, just adds better documentation to previously undocumented or sparsely documented classes and methods.
> Fixing docs

- docker/Dockerfile
- docker/README.md
The changes related to issue 42 will be merged directly into NDF's spyro repository.
> Issue 0042 into NDF's spyro (Dockerfile and related environments)

- spyro/solvers/acoustic_solver_construction_with_pml.py
Simple change to have compatibility with FIredrake's latest API change
> Change split to subfunction

- docker/Dockerfile
- setup.py
- test_integration/test_forward_acoustic.py
- test_integration/test_fwi_acoustic.py
- test_parallel/test_forward.py
- test_parallel/test_fwi.py
Added these markers because of the suggestion on https://github.com/firedrakeproject/firedrake/pull/4115
> added mpi-pytest marker and dependency
